# Session 1: NumPy Fundamentals (2 hours)

**Goal:** Build fluency with array creation, indexing, slicing, and core operations.

| Section | Time | Focus |
|---------|------|-------|
| Setup | 15 min | Import & verify environment |
| Task 1.1 | 30 min | Array creation & indexing |
| Task 1.2 | 1 hr 15 min | NumPy-100 selected exercises |

## Setup (15 min)

In [1]:
import numpy as np

print(f"NumPy version: {np.__version__}")
print("Setup complete!")

NumPy version: 1.26.4
Setup complete!


---
## Task 1.1: Array Creation & Indexing (30 min)

### Exercise 1: Create the following arrays

1. A 1D array `[1, 2, 3, 4, 5]` using `np.array`
2. Even numbers from 0 to 8 using `np.arange`
3. 5 evenly spaced values between 0 and 1 using `np.linspace`
4. A 3x4 matrix of zeros
5. A 2x3x4 tensor of ones
6. A 3x3 matrix of random standard-normal values (set seed=42 for reproducibility)

In [ ]:
# YOUR CODE HERE
arr1 = ...
arr2 = ...
arr3 = ...
arr4 = ...
arr5 = ...

np.random.seed(42)
arr6 = ...

# Print each array and its shape
for name, arr in [("arr1", arr1), ("arr2", arr2), ("arr3", arr3),
                   ("arr4", arr4), ("arr5", arr5), ("arr6", arr6)]:
    print(f"{name}: shape={np.shape(arr)}, dtype={np.array(arr).dtype}")
    print(arr)
    print()

arr1: shape=(5,), dtype=int64
[1 2 3 4 5]

arr2: shape=(5,), dtype=int64
[0 2 4 6 8]

arr3: shape=(5,), dtype=float64
[0.   0.25 0.5  0.75 1.  ]

arr4: shape=(3, 4), dtype=float64
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

arr5: shape=(2, 3, 4), dtype=float64
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]

arr6: shape=(3, 3), dtype=float64
[[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]
 [ 1.57921282  0.76743473 -0.46947439]]



<details>
<summary>💡 Click to see solution</summary>

```python
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.arange(0, 10, 2)          # 0,2,4,6,8
arr3 = np.linspace(0, 1, 5)
arr4 = np.zeros((3, 4))
arr5 = np.ones((2, 3, 4))
np.random.seed(42)
arr6 = np.random.randn(3, 3)
```
</details>


### Exercise 2: Indexing & Slicing

Given the array below, extract:
1. The element at index 3
2. Elements from index 2 to 5 (exclusive)
3. Every other element
4. The array reversed
5. The last 3 elements

In [ ]:
x = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# YOUR CODE HERE
elem_3 = ...
slice_2_5 = ...
every_other = ...
reversed_arr = ...
last_3 = ...

print(f"Element at index 3: {elem_3}")
print(f"Slice [2:5]: {slice_2_5}")
print(f"Every other: {every_other}")
print(f"Reversed: {reversed_arr}")
print(f"Last 3: {last_3}")

<details>
<summary>💡 Click to see solution</summary>

```python
elem_3 = x[3]
slice_2_5 = x[2:5]
every_other = x[::2]
reversed_arr = x[::-1]
last_3 = x[-3:]
```
</details>


### Exercise 3: Slicing vs Fancy Indexing

**Key question:** What is the difference between `arr[1:3]` and `arr[[1, 2]]`?

Run the experiments below and write your explanation.

In [ ]:
original = np.array([10, 20, 30, 40, 50])

# Experiment 1: Slicing returns a VIEW (shares memory)
slice_view = original[1:3]
slice_view[0] = 999
print(f"After modifying slice: original = {original}")

# Reset
original = np.array([10, 20, 30, 40, 50])

# Experiment 2: Fancy indexing returns a COPY
fancy_copy = original[[1, 2]]
fancy_copy[0] = 999
print(f"After modifying fancy index: original = {original}")

**Your explanation (double-click to edit):**

_Write your understanding of the difference here..._

### Exercise 4: 2D Array Indexing

In [ ]:
matrix = np.arange(1, 13).reshape(3, 4)
print("Matrix:")
print(matrix)
print()

# Extract the following:
row_1 = ...           # Second row (index 1)
col_2 = ...           # Third column (index 2)
submatrix = ...       # Top-left 2x2 block
diagonal = ...        # Main diagonal elements
corners = ...         # Four corner elements as a 2x2 array

print(f"Row 1: {row_1}")
print(f"Col 2: {col_2}")
print(f"Submatrix:\n{submatrix}")
print(f"Diagonal: {diagonal}")
print(f"Corners:\n{corners}")

<details>
<summary>💡 Click to see solution</summary>

```python
row_1 = matrix[1, :]
col_2 = matrix[:, 2]
submatrix = matrix[:2, :2]
diagonal = np.diag(matrix)
corners = matrix[[0, 0, 2, 2], [0, 3, 0, 3]].reshape(2, 2)
```
</details>


### Exercise 5: Boolean Indexing

In [ ]:
np.random.seed(0)
data = np.random.randint(-10, 10, size=20)
print(f"Data: {data}")

# Use boolean indexing to:
positives = ...          # All positive values
abs_gt_5 = ...           # Values with absolute value > 5
even_values = ...        # All even values

print(f"Positives: {positives}")
print(f"|x| > 5: {abs_gt_5}")
print(f"Even: {even_values}")

# Replace all negative values with 0 (in a copy)
data_clipped = data.copy()
# YOUR CODE HERE
print(f"Clipped: {data_clipped}")

<details>
<summary>💡 Click to see solution</summary>

```python
positives = data[data > 0]
abs_gt_5 = data[np.abs(data) > 5]
even_values = data[data % 2 == 0]
data_clipped[data_clipped < 0] = 0
```
</details>


### Checkpoint

Can you explain the difference between `arr[1:3]` and `arr[[1, 2]]`?

**Answer (double-click to edit):**

_Your answer..._

<details>
<summary>💡 Click to see explanation</summary>

**`arr[1:3]` — Slicing (view)**  
- Uses a *slice* object `1:3` (start:stop).
- Returns a **view** into the original array: it shares the same underlying memory.
- Modifying the result (e.g. `arr[1:3][0] = 999`) modifies the original `arr`.

**`arr[[1, 2]]` — Fancy indexing (copy)**  
- Uses a *sequence of indices* (list or array) `[1, 2]`.
- Returns a **new array** (a copy); it does not share memory with `arr`.
- Modifying the result does **not** change the original `arr`.

**Summary:** Same elements, different memory behavior. Use slicing when you want speed and don’t need a copy; use fancy indexing when you want a safe, independent copy.
</details>

---
## Task 1.2: NumPy-100 Selected Exercises (1 hr 15 min)

Full set: https://github.com/rougier/numpy-100

Complete the exercises below. For each one, think: *"How would I do this with a for loop? Why is the NumPy version faster?"*

### Group A: Basic Array Operations (Exercises 1-10)

**Q1.** Create a null vector of size 10

In [ ]:
# YOUR CODE HERE


<details>
<summary>💡 Click to see solution</summary>

```python
z = np.zeros(10)
```
</details>


**Q2.** Create a null vector of size 10 but the fifth value is 1

In [ ]:
# YOUR CODE HERE


<details>
<summary>💡 Click to see solution</summary>

```python
z = np.zeros(10)
z[4] = 1
```
</details>


**Q3.** Create a vector with values ranging from 10 to 49

In [ ]:
# YOUR CODE HERE


<details>
<summary>💡 Click to see solution</summary>

```python
z = np.arange(10, 50)
```
</details>


**Q4.** Reverse a vector (first element becomes last)

In [ ]:
# YOUR CODE HERE


<details>
<summary>💡 Click to see solution</summary>

```python
z = np.arange(10, 50)[::-1]
```
</details>


**Q5.** Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
# YOUR CODE HERE


<details>
<summary>💡 Click to see solution</summary>

```python
z = np.arange(9).reshape(3, 3)
```
</details>


**Q6.** Find indices of non-zero elements from `[1, 2, 0, 0, 4, 0]`

In [ ]:
# YOUR CODE HERE


<details>
<summary>💡 Click to see solution</summary>

```python
arr = np.array([1, 2, 0, 0, 4, 0])
z = np.nonzero(arr)[0]
```
</details>


**Q7.** Create a 3x3 identity matrix

In [ ]:
# YOUR CODE HERE


<details>
<summary>💡 Click to see solution</summary>

```python
z = np.eye(3)
```
</details>


### Group B: Indexing and Slicing (Exercises 15-25)

**Q8.** Create a 2D array with 1 on the border and 0 inside (5x5)

In [ ]:
# YOUR CODE HERE


<details>
<summary>💡 Click to see solution</summary>

```python
z = np.ones((5, 5), dtype=int)
z[1:-1, 1:-1] = 0
```
</details>


**Q9.** Pad an existing array (3x3 of ones) with a border of zeros

In [ ]:
# YOUR CODE HERE


<details>
<summary>💡 Click to see solution</summary>

```python
core = np.ones((3, 3), dtype=int)
z = np.pad(core, pad_width=1, mode="constant", constant_values=0)
```
</details>


**Q10.** Create a 5x5 matrix with row values ranging from 0 to 4

In [ ]:
# YOUR CODE HERE


<details>
<summary>💡 Click to see solution</summary>

```python
z = np.tile(np.arange(5), (5, 1))
```
</details>


**Q11.** Create a checkerboard 8x8 matrix using slicing

In [ ]:
# YOUR CODE HERE


<details>
<summary>💡 Click to see solution</summary>

```python
z = np.zeros((8, 8), dtype=int)
z[0::2, 0::2] = 1
z[1::2, 1::2] = 1
```
</details>


**Q12.** Normalize a 5x5 random matrix (values between 0 and 1)

In [ ]:
# YOUR CODE HERE


<details>
<summary>💡 Click to see solution</summary>

```python
np.random.seed(0)  # or any seed
z = np.random.rand(5, 5)
z = (z - z.min()) / (z.max() - z.min())
```
</details>


### Group C: Array Manipulation (Exercises 30-40)

**Q13.** How to find common values between two arrays?

In [ ]:
A = np.array([1, 2, 3, 4, 5])
B = np.array([3, 4, 5, 6, 7])

# YOUR CODE HERE


<details>
<summary>💡 Click to see solution</summary>

```python
common = np.intersect1d(A, B)
```
</details>


**Q14.** Create a random vector of size 10 and sort it

In [ ]:
# YOUR CODE HERE


<details>
<summary>💡 Click to see solution</summary>

```python
z = np.random.rand(10)
z = np.sort(z)
```
</details>


**Q15.** Replace the maximum value by 0 in a random vector

In [ ]:
# YOUR CODE HERE


<details>
<summary>💡 Click to see solution</summary>

```python
z = np.random.rand(10)
z[z.argmax()] = 0
```
</details>


**Q16.** Subtract the mean of each row of a matrix (5x5 random)

In [ ]:
# YOUR CODE HERE


<details>
<summary>💡 Click to see solution</summary>

```python
m = np.random.rand(5, 5)
m = m - m.mean(axis=1, keepdims=True)
```
</details>


**Q17.** Sort an array by the nth column

In [ ]:
# Create a random 5x3 matrix and sort by column index 1
# YOUR CODE HERE


<details>
<summary>💡 Click to see solution</summary>

```python
m = np.random.rand(5, 3)
m = m[m[:, 1].argsort()]
```
</details>


### Group D: Mathematical Operations (Exercises 45-55)

**Q18.** Compute `((A + B) * (-A / 2))` element-wise without creating intermediate arrays (use `np.add`, `np.multiply`, etc. with `out` parameter)

In [ ]:
A = np.ones(3) * 1
B = np.ones(3) * 2

# YOUR CODE HERE


<details>
<summary>💡 Click to see solution</summary>

```python
result = np.empty_like(A, dtype=float)
np.add(A, B, out=result)
np.multiply(result, -A / 2, out=result)
```
</details>


**Q19.** Get the n largest values of an array

In [ ]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# YOUR CODE HERE (hint: np.argpartition)


<details>
<summary>💡 Click to see solution</summary>

```python
indices = np.argpartition(Z, -n)[-n:]
# Or to get values: Z[np.argpartition(Z, -n)[-n:]]
```
</details>


**Q20.** Compute the sum of a vector using different methods and compare speed

In [ ]:
Z = np.random.random(1000000)

# Method 1: Python sum()
%timeit sum(Z)

# Method 2: np.sum()
%timeit np.sum(Z)

# Method 3: Z.sum()
%timeit Z.sum()

# Method 4: np.add.reduce()
%timeit np.add.reduce(Z)

**Q21.** Compute the dot product of two vectors manually (without np.dot), then verify

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Manual dot product
dot_manual = ...

# Verify with NumPy
dot_numpy = np.dot(a, b)

print(f"Manual: {dot_manual}, NumPy: {dot_numpy}, Match: {dot_manual == dot_numpy}")

<details>
<summary>💡 Click to see solution</summary>

```python
dot_manual = np.sum(a * b)
# Or: dot_manual = (a * b).sum()
```
</details>


**Q22.** Compute running (cumulative) sum of a vector

In [ ]:
Z = np.array([1, 2, 3, 4, 5])

# YOUR CODE HERE


<details>
<summary>💡 Click to see solution</summary>

```python
z = np.cumsum(Z)
```
</details>


### Group E: Linear Algebra Basics (Exercises 60-65)

**Q23.** Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [ ]:
# YOUR CODE HERE


<details>
<summary>💡 Click to see solution</summary>

```python
A = np.random.rand(5, 3)
B = np.random.rand(3, 2)
M = A @ B
```
</details>


**Q24.** Create a structured array with `name` (string) and `age` (int) fields

In [ ]:
# YOUR CODE HERE


<details>
<summary>💡 Click to see solution</summary>

```python
dtype = np.dtype([("name", "U10"), ("age", "i4")])
data = np.array([("Alice", 30), ("Bob", 25)], dtype=dtype)
```
</details>


**Q25.** Given a 1D array, negate all elements between 3 and 8 (in-place)

In [ ]:
Z = np.arange(11)

# YOUR CODE HERE

print(Z)

<details>
<summary>💡 Click to see solution</summary>

```python
Z[3:9] *= -1
```
</details>


---
## Session 1 Reflection

**What concept was most surprising?**

_Your answer..._

**What still feels fuzzy?**

_Your answer..._

**Pro Tip recap:** For each exercise above, did you ask yourself *"How would I do this with a for loop? Why is the NumPy version faster?"*